### ISSUE TITLE
Like what you've done

### ISSUE THREAD

**Issue by nilsenj** [dazzz1er/confer#11]
I like what you've done and this seems really great but what I think is how to implement all that functionality with nodejs an redis!
and I hope I will do this in some period of time! Definitely i will do this)

**Comment by dazzz1er** [comment]
Hi @nilsenj ,
After I wrote confer I actually implemented a socket.io and Redis solution for real-time functionality, it was much faster than Pusher! I did not write a port for confer with this new solution though as it still requires a lot of initial setup with installing and using both Redis and socket.io which I feel most users are not keen to do.

If you are working on making something similar, I wish you luck!
