### ISSUE TITLE
Problem creating a new conversation

### ISSUE THREAD

**Issue by HopperCat** [dazzz1er/confer#13]
Im having some trouble when I try to "create" a new conversation with a user, im getting this 404 error: http://my-url/confer/user/2/conversation/NaN/info and a 500 Internal Server Error http://my-url/confer/conversation/find/user/1:  ErrorException in Conversation.php line 87:
array_intersect(): Argument #1 is not an array

It seems as if the Conversations are not being created in the database and I can only chat in the global  conversation.

Can you please help me?

Thank you for your time

**Comment by jetwes** [comment]
This happens when the connection between Confer and your user model is not established.. I had some same issues - mostly namespace related

**Comment by HopperCat** [comment]
Hi jetwes, thank you for your help. I checked my user model and in fact I had a typo there. Also, I had to change a couple of lines in Conversation.php and in helpers.php to convert some objects toArray and now I got it to work. There still seems to be an issue with the "user_id" and the "conversation_id" being flipped.

**Comment by jetwes** [comment]
yeah - that's right. You you have to switch conversation_id and user_id in conversations() (conversation model)

**Comment by dazzz1er** [comment]
Hi @HopperCat ,
Glad to see someone helped you out... I will look to fix some of these issues when I have a spare moment - or feel free to issue a pull request!
Thanks @jetwes for providing a solution!
