### ISSUE TITLE
User to user messaging 

### ISSUE THREAD

**Issue by RokSiEu** [dazzz1er/confer#2]
Hi,

did you think of "private" messaging support (select user(s) from list and start a chat? Because now it looks like you have chat rooms that all users can join.

**Comment by dazzz1er** [comment]
Hi @RokSiEu if you click the users icon (the one that looks like 3 people) below the All chat, you will find a list of users based on whether they are online or not.  Clicking on a user will open a private chat.

You can also start a group chat (and give it a name) by clicking the user+ icon (top of the conversation under the description) on any private conversation, and choosing users to add from the list.

**Comment by RokSiEu** [comment]
Oh. I didn't notice that icon. Thanks for explanation. 

One question, did you use a lot of L5 features / dependencies or it would be easy to fork it to L4 ?

**Comment by dazzz1er** [comment]
Sure, I'm thinking I need to rearrange or make those icons a bit bigger as they can be missed quite easily.

This is my first package so I'm not too sure of the differences between L5 and L4 packages, but I think once you sort out the namespacing and the request validation you'd just be left with adding in your own command bus and re-writing the queue commands as the package makes use of the ShouldBeQueued command trait.

I guess it is relatively L5 reliant in its current form.
