### ISSUE TITLE
WebSocket is closed before the connection is established.

### ISSUE THREAD

**Issue by ghost** [dazzz1er/confer#22]
Hello !

I have a problem with this package, i can't connect to my app :/ 
I have the message : "WebSocket is closed before the connection is established", and I don't know how to resolve it.

I'm using Laravel 5.1.

Thanks for your help !

**Comment by ACmagic** [comment]
Please refer to [WebSocket is closed before the connection is established](https://support.pusher.com/hc/en-us/articles/202085586-WebSocket-is-closed-before-the-connection-is-established)
Besides, confer was not made for L5.1. Please refer to the discussion in #17.

**Comment by ghost** [comment]
Is there any possibility to have confer on laravel 5.1 ? It would be awesome ! 
I can help if it's possible ! :)

**Comment by dazzz1er** [comment]
hi @cyrilblankaert if you see issue #17 you'll see a working L5.1 version of confer has been created by a user. He may be happy to supply you with his code or some hints if you ask.

As for the current package I would love to update it to 5.1 and 5.2 compatibility myself (and implement a Redis + socket.js implementation) but do not expect to find the time to do this for a few months!
