### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by huyle2607** [dazzz1er/confer#25]
I know it is a really really bad question but how do I make it work on my page. I've tried many way but it doesn't work. I just need someone to guide me where to put all the code. I'm using Laravel 5.1 by the way.

**Comment by hallmichael** [comment]
You can check out my fork, its not perfect but it works with 5.1 just check the updated readme and go from there. dazzz1er is likely to rewrite and publish a proper 5.2 release I just made the changes to get it working with the existing code.

Forked repo here: https://github.com/hallandcodigital/confer

**Comment by huyle2607** [comment]
Thanks a lot. I think the problem in my project is that it has the wrong links to its file. Most of it I have to add more folder name to it. Still working on it.

**Comment by huyle2607** [comment]
@hallmichael  Thanks for your fork. I managed to make it work however I still have some problems with this package. 
First of all, when I logged in. I cannot see anyone online even though I logged in with several accounts from different browsers.
Second thing is that when I send a message, I have to refresh the page to see it and in the console after I clicked send, there was an Internal Server Error (500). 
![screenshot_3](https://cloud.githubusercontent.com/assets/15210474/15632557/549dd61e-25c0-11e6-9250-0ed7106a4c82.png)

Please help me with these problems! I don't know how to fix it.

**Comment by hallmichael** [comment]
@huyle2607 - sorry I am no pro at pusher! It is saying your auth value for pusher is incorrect, I could only guess the config is the issue, you can email me your code/post it here and I can compare to my working instance.

I would also need to see the 500 internal server error in your laravel.log.

**Comment by huyle2607** [comment]
@hallmichael  I think those Warnings have nothing to do with 500 Internal Server Error. When I click on the error, it leads to network tab with this information: 
![screenshot_2](https://cloud.githubusercontent.com/assets/15210474/15661529/7683b426-2712-11e6-9861-7be00d61e6bb.png)

Have you ever seen this problem before?

**Comment by huyle2607** [comment]
@hallmichael  Ok. This might be weird but I just checked your fork and I saw that in your  MessageWasSent.php code was different from the original code. I changed and it works. Maybe it's because of Laravel 5.1 I think.
However it leads to another thing. When I open 2 windows to chat. It only works on one window. The other window needs to refresh to see the coming message.

**Comment by huyle2607** [comment]
@hallmichael  Hi, I managed to make it work perfectly and I can chat globally now. Thanks to all your update for laravel 5.1. Unfortunately, it still has a problem which I cannot chat privately with another person. When I click on one user, it creates a row in confer_conversations table between 2 people so clearly it works perfectly in the database however on the browser nothing happens.
![screenshot_3](https://cloud.githubusercontent.com/assets/15210474/15669417/7e6a3894-274a-11e6-8c9a-adacd0c9db99.png)

It works globally only.

_It also said as in the picture as I clicked on user icon_
![screenshot_4](https://cloud.githubusercontent.com/assets/15210474/15669661/ab8ea7d2-274b-11e6-841f-048f0f33410a.png)

_And this error too_
![screenshot_5](https://cloud.githubusercontent.com/assets/15210474/15669906/e2fda578-274c-11e6-9a49-286357978910.png)

**Comment by huyle2607** [comment]
@hallmichael Finally, I fixed everything and now my project works perfectly. The problem was in the Helpers.php file. It has a function implode() and it needs an array but Laravel seems not to know $items as an array so I have to declare $items = array(). And that's it. 

_I'm so sorry if this issue annoys you. This issue is close now! :)_

**Comment by hallmichael** [comment]
@huyle2607 nice work! so the private chat works too? cool stuff. I just wish I had more time!

**Comment by huyle2607** [comment]
Yeah! The private chat works well too. Thanks for your Laravel 5.1 update, though :)) Cheer!

**Comment by dazzz1er** [comment]
Thanks for the issue and posting the fix @huyle2607 - should be helpful when I make the jump to an official L5.2 version! I've been working away from Laravel (actually with iOS) for a while so these kinds of issues are good to know as I have not kept up with the changes.

Thanks @hallmichael for the fork in the mean time and helping where you can with issues!
