### ISSUE TITLE
Get a null result from $channel_info in Confer.php file

### ISSUE THREAD

**Issue by huyle2607** [dazzz1er/confer#26]
There is a problem when I integrate this package into my project. When I created a new project, confer package worked perfectly but when I put into my working project I got this error. And it said that $channel_info was null and it could not get any user from $online_users.
![screenshot_2](https://cloud.githubusercontent.com/assets/15210474/15799762/24529dc0-2a91-11e6-8e2e-e5fdc53a3449.png)

Why is there no channel to be got?
Does anybody know how to fix?

**Comment by perffy** [comment]
How did u manage to resolve it ? I have now the same error. Please help me

**Comment by perffy** [comment]
i found the solution. My pusher keys were empty :)
