### ISSUE TITLE
Mentions

### ISSUE THREAD

**Issue by RokSiEu** [dazzz1er/confer#3]
Few days ago I've implemented mentions (in L4) using At.js which you can find here https://github.com/ichord/At.js 

it is great and simple to use so I hope you will find it useful.

**Comment by dazzz1er** [comment]
Thanks @RokSiEu - mentions is one of the features I was looking to implement next! I will definitely take a look at what you suggested.

**Comment by RokSiEu** [comment]
No problem. 
I'm closing this one as this is not an real issue.
